name: "Publish"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    permissions: write-all
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '21'
          java-package: jdk+fx
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle jpackage
        run: ./gradlew jpackage

      - name: Gradle zipjpackage
        run: ./gradlew zipjpackage

      - name: Archive build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.os }}-build-artifacts
          path: dist

  release:
    permissions: write-all
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
        with:
          name: ubuntu-latest-build-artifacts
          path: dist
      - uses: actions/download-artifact@v6
        with:
          name: macos-latest-build-artifacts
          path: dist
      - uses: actions/download-artifact@v6
        with:
          name: windows-latest-build-artifacts
          path: dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ github.event.inputs.version }}"
          prerelease: false
          title: "Release v${{ github.event.inputs.version }}"
          files: |
            dist/*.deb
            dist/*.dmg
            dist/*.msi
            dist/*.zip